### ISSUE TITLE
REST vs Javascript Library

### ISSUE THREAD

**Issue by mlebarron** [ninjatronic/angular-kinvey#1]
Hey, found this a few days ago and I've started using it myself... Curious why you went with using the REST api instead of wrapping their JS library. I can see benefits on both sides I guess so I'm wondering your thought process.

Hopefully I'll be able to get some pull requests in, assuming I continue building out on Kinvey.

**Comment by ninjatronic** [comment]
There were a few reasons:
- Wrapping the javascript library directly would have meant having to inject `$rootScope` into the service and 'wrap' all the javascript API calls in `$apply()` calls to get them to work with the promise model
- There is some direct discussion with some of the developers at Kinvey about the way they'd like to go about it, and we agreed that it would be best to use the `$resource` pattern where possible to give access to objects in the backend to enable nice OO things like...

``` javascript
$kinvey.alias('badger', 'Badger');
var badger = new $kinvey.Badger();
badger.fName = 'Michael';
badger.lName = 'LeBarron';
badger.$save();
```
- It allows for `$http` interceptors to be used
- It allows for `$httpBackend` to be used in test code
- It just seemed like the "Angular" way of doing it :)

There is a loose roadmap for development, hopefully with an official tagged and bowerable release in the near future. I'm going to look at putting it on the wiki very soon. Pull requests are very welcome.

**Comment by mlebarron** [comment]
awesome. I've been away from Angular for a few months so I'm getting 
back up to speed at the moment. Are you working with Kinvey on the 
roadmap? They're about a 10 minute walk from me :)

Pete Martin wrote:

**Comment by ninjatronic** [comment]
I've been consulting with a couple of developers there about what features to put in and some challenges we've faced getting here so far. I'd be interested in looking at your code that uses this of you are open sourcing it?

**Comment by mlebarron** [comment]
The current stuff is an internal project. So far I've only had to add a 
custom endpoint function, roughly copy/pasted to prove it would work. 
Would be nice if endpoints were aliasable, but custom endpoints probably 
aren't the highest priority items.

https://github.com/mlebarron/ngKinvey/commit/6ce9de513291d9746d13a3df18bf2ddbb239c5da

**Comment by ninjatronic** [comment]
RPC endpoints and file uploading are going to be added in the immediate future. I'd imagine that they will return standard promises rather than resource objects as having the OO methods on the results doesn't really make a lot of sense.

**Comment by ninjatronic** [comment]
Hi @mlebarron 

You can observe the progress of issues #2 and #3 which are going to be included next

Thanks

**Comment by mlebarron** [comment]
Awesome. Will contribute when I can.

**Comment by ninjatronic** [comment]
Hi @mlebarron 

RPC endpoints and file functionality are added to the library now.

If you need any help incorporating the new features feel free to raise an issue :)

Thanks
