### ISSUE TITLE
column named "handles"

### ISSUE THREAD

**Issue by mlebarron** [ninjatronic/angular-kinvey#16]
I haven't tracked this down yet so it's possible it's not the library, I'm using angular 1.2.3

One of the columns I have is called "handles" and it always ends up empty. If I rename it to twitter_handles, it correctly returns it's data. In the get when angular.fromJson(data) is called it's set correctly in the data variable.

```
{"_id":"52852d6812b138af6f000f2e","name":"Disney","nameSearch":"disney","handles":{"all":["@disney","@disneystore"],"default":"@disney"},"twitter_handles":{"all":["@disney","@disneystore"],"default":"@disney"},"_acl":{"creator":"kid_PPbOfZeLmO"},"_kmd":{"lmt":"2013-12-06T16:30:19.569Z","ect":"2013-11-14T20:07:04.857Z"}}
```

but by the time it gets to the view handles is empty. 

```
{"_id":"52852d6812b138af6f000f2e","name":"Disney","nameSearch":"disney","handles":"","twitter_handles":{"all":["@disney","@disneystore"],"default":"@disney"},"_acl":{"creator":"kid_PPbOfZeLmO"},"_kmd":{"lmt":"2013-12-06T16:30:19.569Z","ect":"2013-11-14T20:07:04.857Z"}}
```

like I said I haven't had a chance to really dig into it, so I'll let you know if I figure out what's going on, but if there's any ideas out there that would be great.

**Comment by mlebarron** [comment]
little more info, it's happening when I use .get but not .query...

actually check that, it's working when I query something that references this and use resolve, so it's one level deeper in the object, so not the same.

**Comment by ninjatronic** [comment]
I've been trying to reproduce this issue as you have describe it but I have not been able to so far. Can you check that my scenario tests are along the right lines? See commit 616e6fd17d61456362db71130306fb3e6a6d5163 for examples.

**Comment by mlebarron** [comment]
Will do when I get a chance. Will also work on minimizing all other code and building a sample test case to duplicate on my side. 

Michael LeBarron
617.538.2037
@mlebarron

**Comment by ninjatronic** [comment]
Hi @mlebarron 

Wondering if you made any progress with isolating the cause of this issue? I still have not been able to reproduce it.

Cheers

**Comment by mlebarron** [comment]
was away for a few days... 

Nope, just went through trying to recreate it, with the exception of renaming some files, should be the same code I was on before, and I'm unable to duplicate... so, consider it solved I guess. 

I did have to recreate the column on the kinvey side, since I had removed it... at a loss at the moment, but problem is gone.
