### ISSUE TITLE
save broken

### ISSUE THREAD

**Issue by mlebarron** [ninjatronic/angular-kinvey#17]
bed772d causes me to get 

```
TypeError: Object function (className) {
                        return augmentObjectDef(
                            augmentForMongo(
                                $resource(baseUrl + appdata + appKey + '/' + className + '/:_id', {_id: '@_id'}, {
... omitted...
                    } has no method 'update'
```

I'm using an alias
$kinvey.alias('campaigns', 'Campaigns');
when doing $kinvey.Campaigns.save(campaign);

**Comment by olamarche** [comment]
Hi,

I got a similair error...
Here is the stacktrace on my console:

![capture decran 2013-12-06 a 22 51 45](https://f.cloud.github.com/assets/5215631/1697653/43847a5e-5ef3-11e3-9f71-0e03664d5999.png)

Basic stuff, I'm using a alias for my collection, then I get my current object, then, I'm trying to save without modifications.

```
var Fichier = $kinvey.Object('FichierCollections');
$kinvey.alias('FichierCollections', 'Fichier');
currentFichier = $kinvey.Fichier.get({_id: fichierId});
$kinvey.Fichier.save(currentFichier);
```

**Comment by ninjatronic** [comment]
This should be fixed now.

@mlebarron @olamarche Are you guys using the latest source from the repo or a bower release? Since this is such a critical issue I'm happy to move the next bugfix release date (13th December) forward if you are using the bower latest and need it sooner.

**Comment by mlebarron** [comment]
I use the repo so doesn't matter to me.
