### ISSUE TITLE
Compound Query example?

### ISSUE THREAD

**Issue by aaronksaunders** [ninjatronic/angular-kinvey#24]
Looking for an example of how to do a compound query like documented in the official Kinvey documentation?

http://devcenter.kinvey.com/angular/guides/datastore#CompoundQueries

**Comment by aaronksaunders** [comment]
Just followed the link to the mogo documentation and will see if i can get it to work, if not I will re-open the ticket.

**Comment by ninjatronic** [comment]
Hi @aaronksaunders 

If you can't get it to work, post back and I'll be happy to help you write an example query

Cheers
