### ISSUE TITLE
Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by kenhkan** [ninjatronic/angular-kinvey#7]
Hi @ninjatronic, great library. Somehow though the file API doesn't quite work. Following the doc, namely:

```
var file = new $kinvey.File({
    _filename: 'myFile.txt'
});
file.$save('text/plain');
file.$promise.then(function() {
    var upload = file.$upload('this is the file contents\r\n', 'text/plain');
    upload.$promise.then(function() {
        $window.alert('file upload complete');
    });
);
```

An error is thrown complaining that `file.$promise` is undefined. Upon looking at the source it is indeed undefined. I then tried the public file sample in the doc:

```
$kinvey.File.upload({
    meta: 'metadata map',
    _id: 'optionalId',
    _public: true
}, 'text/plain', 'text file contents', 'filename.txt')
    .then(function(file) {
        console.log('file uploaded successfully');
        console.log(file); // this is a $resource object
    });
```

This throws another error:

```
TypeError: Cannot read property 'protocol' of undefined
    at urlIsSameOrigin (http://localhost:8888/vendor.js:22337:17)
    at $http (http://localhost:8888/vendor.js:16253:23)
    at http://localhost:8888/vendor.js:34748:2141
    at r (http://localhost:8888/vendor.js:34748:1160)
    at Function.$get.a.upload (http://localhost:8888/vendor.js:34748:2125)
```

I've also tried a bunch of different configuration according to test cases and source but to no avail. And the app is authenticated and logged in with other parts of the app working. Any idea what went wrong? Thanks.

**Comment by ninjatronic** [comment]
Hi @kenhkan 

Thanks for your detailed and comprehensive bug report :)

I have added a commit that will address the first part of your issue, which was a bug. I'm looking at the second part of your issue now.

**Comment by ninjatronic** [comment]
Hi @kenhkan 

Your second issue was a documentation hangover from a previous version. I've updated the docs, the second code sample should look like this:

``` javascript
var file = new $kinvey.File({
    _filename: 'myFile.txt',
    _public: true
});
file.$save('text/plain');
file.$promise.then(function() {
    var upload = file.$upload('this is the file contents\r\n', 'text/plain');
    upload.$promise.then(function() {
        $window.alert('file upload complete');
    });
);
```

Please let me know if this doesn't work for you.

Thanks

**Comment by kenhkan** [comment]
This works great! Thanks for the quick update. The only thing that I'm struggling is the inability to upload binary files. It appears that the underlying $http doesn't play nice with Kinvey. Have you had experience with getting binary files on Kinvey via $http? Thanks.

**Comment by ninjatronic** [comment]
Hi @kenhkan 

I've looked into the binary file upload issue. You can refer to [this Gist](https://gist.github.com/ninjatronic/7718174) which demonstrates how to upload binary files with angular-kinvey. I've managed to upload/download large images with this demo today. Be sure to replace the bower version of angular-kinvey with the latest from the repo.

Thanks

**Comment by kenhkan** [comment]
@ninjatronic It works perfectly! Thanks.

By the way, there is another doc hangover. Under section "Downloading" on page "Files", right now it's:

```
var file = $kinvey.File.get('fileId');
file.$promise.then(function() {
    var download = file.$download();
    download.$promise.then(function(filedata) {
        $window.alert('file download complete');
        console.log('filedata: '+filedata);
    });
});
```

but it should be:

```
var file = $kinvey.File.get({ id: 'fileId' });
...
```

Closing now.

**Comment by ninjatronic** [comment]
Thanks :)
